### ISSUE TITLE
`Result::unwrap()` on an `Err` value: No touchbar device found

### ISSUE THREAD

**Issue by Ikuyu** [WhatAmISupposedToPutHere/tiny-dfr#24]
Just install Pop!_OS without Nvidia on my 13 inch Macbook Pro 2019 with integrated GPU. All went well. Everything is working after following the instructions here:  https://t2linux.org/ except for the touchbar. So I can´t use ESC, FN-keys etc.

I've installed tiny-dfr with the command: $ sudo apt install tiny-dfr. Then I've restarted the laptop, but... no touchbar. Then I've run 'sudo apt install tiny-dfr' but... no touchbar. Instead I got the message: 

thread 'main' panicked at src/main.rs:658:43:
called `Result::unwrap()` on an `Err` value: No touchbar device found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Any help on this?

**Comment by WhatAmISupposedToPutHere** [comment]
Unfortunately, i can not provide that much support for intel machines, since i do not have any t2 macbooks. To the first glance, the issue is that the t2 display output can't be found, but i can't offer any further help. You should try asking in the t2 discord for help.

**Comment by PJET2000** [comment]
@Ikuyu  Have you found a solution yet?

**Comment by Ikuyu** [comment]
Unfortunately not. When I rebooted into macOS and then again into popOS I saw the Touch Bar a brief moment, but after logging out/in it disappeared again. Also, when I saw it I got the message: Result::unwrap() no Touch Bar found. Same with Fedora. I removed popOS and installed the T2 Fedora Gnome edition. Now the Touch Bar remains visible, but when I run your Touch Bar app, it keeps giving me the same message.

**Comment by Grammercy** [comment]
Same issue on Arch, rebooting w/o booting into macos seems to work most of the time. The difference between working and failing appears to be the existence of /dev/dri/card1. When that device exists everything works, and when it doesnt the touchbar disappears

**Comment by sharpenedblade** [comment]
The bug is in the t2 kernel driver. There is nothing tiny-dfr can do so this issue should be closed.

**Comment by ssleert** [comment]
Any updates?

**Comment by WhatAmISupposedToPutHere** [comment]
This is a driver-related bug on t2
