### ISSUE TITLE
Please make brightness conffigurable

### ISSUE THREAD

**Issue by aikrahguzar** [WhatAmISupposedToPutHere/tiny-dfr#29]
I think it would be nice to have some more control over brightness:
1) Without adaptive brightness, please make the default brightness configurable.
2) Less important but it would be nice to have dimmed value to be configurable too.
3) With adaptive brightness please make the argument to `powf` configurable. The current square root is not a good setting for those like me who use very low brightness. My usual screen brightness is `5%` which means that with adaptive brightness on the touch bar brightness is `25%` which is very bright.

**Comment by WhatAmISupposedToPutHere** [comment]
I have changed the adaptive brightness mode so it is scaled by a configurable brightness value. To me, when testing in a completely dark room, with screen set to 5% and brightness scale to 128, the touchbar doesn't look very bright compared to the primary screen

**Comment by aikrahguzar** [comment]
> I have changed the adaptive brightness mode so it is scaled by a configurable brightness value. To me, when testing in a completely dark room, with screen set to 5% and brightness scale to 128, the touchbar doesn't look very bright compared to the primary screen

Thanks a lot for this. I still think it would be better if the square root was not there but with your changes, I can fiddle with brightness scale to get what I want. 

Thanks again!

**Comment by aikrahguzar** [comment]
I tried building with the changes made today and they work but it seems like they have broken config file precedence. Change the file in `/etc/tiny-dfr/config.toml` has no effect as least for `MediaLayerDefault` and `ActiveBrightness`.

**Comment by WhatAmISupposedToPutHere** [comment]
Unable to reproduce, the steps are as follows:

1. Start tiny dfr, observe the touchbar being bright and f-key layer being shown by default.
2. Change MediaLayerDefault to true in the config file and save the file, observe the switch to media layer
3. Change ActiveBrightness to 5 and save the file, observe touchbar getting much dimmer.
4. Stop tiny-dfr
5. Change MediaLayerDefault to false in the config file and save the file.
6. Start tiny-dfr
7. Observe the default layer being the f-key layer.

**Comment by aikrahguzar** [comment]
> Unable to reproduce, the steps are as follows:
> 
>     1. Start tiny dfr, observe the touchbar being bright and f-key layer being shown by default.
> 
>     2. Change MediaLayerDefault to true in the config file and save the file, observe the switch to media layer
> 
>     3. Change ActiveBrightness to 5 and save the file, observe touchbar getting much dimmer.
> 
>     4. Stop tiny-dfr
> 
>     5. Change MediaLayerDefault to false in the config file and save the file.
> 
>     6. Start tiny-dfr
> 
>     7. Observe the default layer being the f-key layer.

It was a stupid typo from me. I am sorry for the noise.
