### ISSUE TITLE
Input driver does not support machines with missing calibration data.

### ISSUE THREAD

**Issue by mattsays** [WhatAmISupposedToPutHere/tiny-dfr#31]
Hi, 
I have just installed Asahi Linux with KDE on my macbook pro 13" with M1 and I have tried to use tiny-dfr (which also appears to not being enabled by default on sytemd) and it only manages to control touchbar display. However the bar touch input seems to not work.

Can I ran any command to see all of the raw events of the touchbar?

Thanks in advance.

**Comment by WhatAmISupposedToPutHere** [comment]
First - what exactly do you mean by "Asahi Linux" - the Arch based distro or the Fedora based one? 


The service is enabled by default, but the default rules start it on detecting the digitizer device, so, since you do not get touch input, the device might not be detected. Maybe run asahi-diagnose and attach the output here?

**Comment by WhatAmISupposedToPutHere** [comment]
The diagnose shows that you are missing the "Z2" device, which is the touchscreen digitizer. Are you using the stock kernel? How old is this installation? Have you tried updating everything, doing update-m1n1, and so on?

**Comment by mattsays** [comment]
I installed the stock asahi fedora with kde yesterday so everything should be updated.
How where can I see info about my digitizer?

**Comment by WhatAmISupposedToPutHere** [comment]
I would still recommend updating everything in fedora, just in case. As to why it is not detected - good question, i do not see it even trying to probe the device in dmesg.

**Comment by mattsays** [comment]
Yeah, I am sure that everything is updated as I ran "dnf upgrade" and the touch issue remains. Maybe it could be related to the corresponding apple_z2 kernel module?
The only thing that could be the problem is the fact that my touchbar has been recently replaced with another one. So this new one could be not apple official and thus not using the expected hardware ids?

**Comment by WhatAmISupposedToPutHere** [comment]
That may or may not be important. Was it an apple replacement or an aftermarket one? If it was aftermarket - your calibration data might be from a wrong device. Can you try setting m1n1 to verbose boot, and looking if anything is suspicious in the logs? If the logs scroll by too fast, one solution is to use your phone's camera in slow-mo mode.

**Comment by mattsays** [comment]
I don't actually know if original or not. How can I boot it up in verbose mode?

**Comment by WhatAmISupposedToPutHere** [comment]
Whether the hardware is original or not is irrelevant, the question is whether it was done by apple or a random repair shop. For verbose mode - refer to this guide https://github.com/AsahiLinux/docs/wiki/m1n1:User-Guide#backdoor-proxy-mode-in-stage-1-release-builds

**Comment by mattsays** [comment]
I tried to do so and I don't see anything related to that.

**Comment by mattsays** [comment]
I tried to do so and I don't see anything related to that.

**Comment by WhatAmISupposedToPutHere** [comment]
Can you please check if `/sys/firmware/devicetree/base/soc/spi@235100000/touchbar@0/` exists on your system, what is the file list, and if the file `status` is present - what are it's contents.

**Comment by mattsays** [comment]
The touchbar folder contains the following files and  status file says "disabled".
[touchbar_folder.txt](https://github.com/WhatAmISupposedToPutHere/tiny-dfr/files/14113865/touchbar.txt)

**Comment by WhatAmISupposedToPutHere** [comment]
Please look through m1n1 verbose logs once again, and see if "ADT: Failed to get multi-touch-calibration..." is present

**Comment by mattsays** [comment]
If that is the case is there any way I can do the calibration?

**Comment by WhatAmISupposedToPutHere** [comment]
Unlikely. The good thing is that macos is capable of somehow initializing a calibration-less touchscreen, so i might be able to look at how it does it and implement something similar in linux. No promises however.

In addition - this is a missing feature in the kernel driver, not tiny-dfr.

**Comment by mattsays** [comment]
Ok thanks anyway.  I will also try digging more deeply into it and keep you updated.

**Comment by itsnebulalol** [comment]
I'm having the same issue. MacBook Pro (13", M1, 2020) running NixOS. I cannot get verbose output right now, but I suspect I'm missing a kernel module. I'm using the asahi-edge kernel.

> Can you please check if `/sys/firmware/devicetree/base/soc/spi@235100000/touchbar@0/` exists on your system, what is the file list, and if the file `status` is present - what are it's contents.

The status file is not present for me.

**Comment by WhatAmISupposedToPutHere** [comment]
> The status file is not present for me.
You have a separate issue.

> Running NixOS
This is most likely the problem. Make sure that you have all the required modules loaded, apple_z2 is the one needed for the input to work.

**Comment by itsnebulalol** [comment]
> apple_z2 is the one needed for the input to work.

Yep, got it to work after adding that as a kernel module and using a `INPUT_TOUCHSCREEN y` kernel patch. Thanks!

**Comment by WhatAmISupposedToPutHere** [comment]
drivers should now support skipping calibration data if it is not present
