### ISSUE TITLE
run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### ISSUE THREAD

**Issue by termaulmaul** [WhatAmISupposedToPutHere/tiny-dfr#35]
root@localhost:/home/ubuntu/Downloads/tiny-dfr-0.2.0/target/debug# ./tiny-dfr 
thread 'main' panicked at src/main.rs:319:101:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by bruhderek** [comment]
I have the same error. If you read the code on that line, you need to make the file `/usr/share/tiny-dfr/config.toml`. Idk if this is intentional but theres another variable that points to the correct location, `/etc/tiny-dfr/config.toml.`

**Comment by WhatAmISupposedToPutHere** [comment]
Fixed by 9a4dc601b709786f79f3d077ed18a88273d1ff4c
