### ISSUE TITLE
tiny-dfr missing from aur

### ISSUE THREAD

**Issue by tilkinsc** [WhatAmISupposedToPutHere/tiny-dfr#39]
This package isn't on aur despite https://wiki.t2linux.org/guides/postinstall/ ref: https://aur.archlinux.org/packages?O=0&K=tiny-dfr

**Comment by WhatAmISupposedToPutHere** [comment]
This repo is for asahi (M-series macs) version of tiny-dfr, the T2 version is a fork. Please ask on the T2 discord for help with this issue.
