### ISSUE TITLE
Cannot add more than Prog4

### ISSUE THREAD

**Issue by bcv** [WhatAmISupposedToPutHere/tiny-dfr#40]
In a configuration (attached) where I add Prog5, the program falls back to basic mode with function keys 
[config.txt](https://github.com/WhatAmISupposedToPutHere/tiny-dfr/files/15220132/config.txt)

**Comment by WhatAmISupposedToPutHere** [comment]
You are not running the version of tiny-dfr from this repo, but most likely this one: https://github.com/kekrby/tiny-dfr Please file this issue on their repo
