### ISSUE TITLE
Is it possible to have a larger button?

### ISSUE THREAD

**Issue by AdityaGarg8** [WhatAmISupposedToPutHere/tiny-dfr#42]
I wonder if it's possible to have a larger button. Something like button multiplier in the config?

**Comment by WhatAmISupposedToPutHere** [comment]
Everything is possible, but you would have to rewrite the button render code, hit test, and partial redraw. Probably also the button state tracker. Patches welcome :P

**Comment by AdityaGarg8** [comment]
I tried but didn't manage to get the touch working properly. Hope someone gets it working.

**Comment by AdityaGarg8** [comment]
Thanks for the feature!

Will update the T2 Macs build once a new release is made.
