### ISSUE TITLE
Touchbar registering as touchscreen input

### ISSUE THREAD

**Issue by themg95** [WhatAmISupposedToPutHere/tiny-dfr#45]
I'm on hyprland and while the buttons on my touchbar work, it also makes my wm think that it's a touchscreen that's controlling my main screen. For example, if i press f12, my mouse will move to the right edge of my screen and if i drag my finger across the whole touchbar, my cursor moves as well

**Comment by WhatAmISupposedToPutHere** [comment]
Does the hyprland compositor have correct seat handling?

**Comment by themg95** [comment]
yup that was the issue :woman_facepalming: tysm
