### ISSUE TITLE
2019 16,1 mackbook. The touch bar worked for a few minutes and thereafter it failed. Dependency issue. 

### ISSUE THREAD

**Issue by steelliberty** [WhatAmISupposedToPutHere/tiny-dfr#46]
Hi -- Thank you for any help you might provide do to solve this problem. I like having function keys -- 

Sep 14 17:01:56 steelliberty systemd[1]: tiny-dfr.service: Job tiny-dfr.service/start failed with result 'dependency'.
Sep 14 17:01:56 steelliberty systemd[1]: dev-tiny_dfr_backlight.device: Job dev-tiny_dfr_backlight.device/start failed with result 'timeout'.
Sep 14 17:01:56 steelliberty systemd[1]: Unnecessary job was removed for dev-tiny_dfr_display.device - /dev/tiny_dfr_display.
░░ Subject: A start job for unit dev-tiny_dfr_display.device has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit dev-tiny_dfr_display.device has finished with a failure.
░░ 
░░ The job identifier is 4127 and the job result is collected.
Sep 14 17:01:56 steelliberty polkitd[888]: Unregistered Authentication Agent for unix-process:6640:309592 (system bus name :1.153, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale C.UTF-8) (disconnected from bus)
Sep 14 17:02:30 steelliberty dbus-daemon[884]: [system] Activating service name='org.kde.powerdevil.backlighthelper' requested by ':1.57' (uid=1000 pid=1811 comm="/usr/lib/x86_64-linux-gnu/libexec/org_kde_powerdev") (using servicehelpe>
Sep 14 17:02:30 steelliberty dbus-daemon[884]: [system] Successfully activated service 'org.kde.powerdevil.backlighthelper'
Sep 14 17:08:41 steelliberty dbus-daemon[884]: [system] Activating service name='org.kde.powerdevil.backlighthelper' requested by ':1.57' (uid=1000 pid=1811 comm="/usr/lib/x86_64-linux-gnu/libexec/org_kde_powerdev") (using servicehelpe>
Sep 14 17:08:41 steelliberty dbus-daemon[884]: [system] Successfully activated service 'org.kde.powerdevil.backlighthelper'

**Comment by WhatAmISupposedToPutHere** [comment]
You are using a t2 mac, and the display driver for them is... not great. I only have m1 machines, and can't help with t2 ones, but i recommend talking to people on t2 linux discord, they might be able to help you https://wiki.t2linux.org/

**Comment by WhatAmISupposedToPutHere** [comment]
This is a driver-related bug on t2
