### ISSUE TITLE
What are the supported models?

### ISSUE THREAD

**Issue by RealFX-Code** [WhatAmISupposedToPutHere/tiny-dfr#51]
It doesn't seem to work on my MacBookPro13,2 no matter what I try.

**Comment by WhatAmISupposedToPutHere** [comment]
The software in this repo should support everything with a touch bar, as long as the drivers are functional. You most likely have some sort of a driver issue that prevents it from starting. For arm (m1/m2) macs, feel free to open issues about drivers on this repo, for intel - please use the t2linux discord. https://t2linux.org/

**Comment by RealFX-Code** [comment]
Thing is, my mac is in that wierd period of having a touchbar, but not having the T2 chip, so the people in the T2 linux discord server won't help me.

**Comment by WhatAmISupposedToPutHere** [comment]
Which is strange, since the udev rules and similar configs to make it work on t1 touchbars were contributed by t2linux people. Unfortunately, they are in fact the best people to ask, i only know how the m1 drivers work and have no idea about the intel devices.

**Comment by RealFX-Code** [comment]
When running it, it just throws: `/dev/dri/card0: Device or resource busy (os error 16)`, Where should I ask? I'm assuming the gentoo channel since that's what my host os is.

**Comment by WhatAmISupposedToPutHere** [comment]
Most likely. However, from what i remember t2 gentoo wasn't well maintained and you may have better success running other t2 distros

**Comment by RealFX-Code** [comment]
> Most likely. However, from what i remember t2 gentoo wasn't well maintained and you may have better success running other t2 distros

well, again. My machine isn't a T2 machine so most of the stuff I'm dealing with is just gentoo stuff, and I'm not really reliant on the T2Linux project. But I can ask there. Thanks!
I'll keep this issue open until I find a fix, if I do.

**Comment by WhatAmISupposedToPutHere** [comment]
For this specific purpose, it is pretty much a t2 machine, with only minor differences.

**Comment by RealFX-Code** [comment]
> For this specific purpose, it is pretty much a t2 machine, with only minor differences.

Hoping they don't get fussy about it this time 👀

**Comment by RealFX-Code** [comment]
I got it working with the ebuild from https://codeberg.org/vimproved/t2-overlay/src/branch/master/app-laptop/tiny-dfr.

I had to clone the driver from https://github.com/almas/macbook12-spi-driver and apply this patch to it:
```patch
diff --git a/apple-ib-als.c b/apple-ib-als.c
index 9cb4347..5c4f26b 100644
--- a/apple-ib-als.c
+++ b/apple-ib-als.c
@@ -645,7 +645,7 @@ error:
        return rc;
 }

-static int appleals_platform_remove(struct platform_device *pdev)
+static void appleals_platform_remove(struct platform_device *pdev)
 {
        struct appleib_device_data *ddata = pdev->dev.platform_data;
        struct appleib_device *ib_dev = ddata->ib_dev;
@@ -658,10 +658,10 @@ static int appleals_platform_remove(struct platform_device *pdev)

        kfree(als_dev);

-       return 0;
+       return;

 error:
-       return rc;
+       return;
 }

 static const struct platform_device_id appleals_platform_ids[] = {
diff --git a/apple-ib-tb.c b/apple-ib-tb.c
index 2b1763e..57b0b90 100644
--- a/apple-ib-tb.c
+++ b/apple-ib-tb.c
@@ -1259,7 +1259,7 @@ error:
        return rc;
 }

-static int appletb_platform_remove(struct platform_device *pdev)
+static void appletb_platform_remove(struct platform_device *pdev)
 {
        struct appleib_device_data *ddata = pdev->dev.platform_data;
        struct appleib_device *ib_dev = ddata->ib_dev;
@@ -1272,10 +1272,11 @@ static int appletb_platform_remove(struct platform_device *pdev)

        appletb_free_device(tb_dev);

-       return 0;
+       return;

 error:
-       return rc;
+//     return rc;
+    return;
 }

 static const struct platform_device_id appletb_platform_ids[] = {
diff --git a/apple-ibridge.c b/apple-ibridge.c
index b176e32..858fd33 100644
--- a/apple-ibridge.c
+++ b/apple-ibridge.c
@@ -898,7 +898,7 @@ MODULE_DEVICE_TABLE(acpi, appleib_acpi_match);
 static struct acpi_driver appleib_driver = {
        .name           = "apple-ibridge",
        .class          = "topcase", /* ? */
-       .owner          = THIS_MODULE,
+       //.owner                = THIS_MODULE,
        .ids            = appleib_acpi_match,
        .ops            = {
                .add            = appleib_probe,
```

**Comment by RealFX-Code** [comment]
Nevermind, I seem to have gotten too excited about the module working, tiny-dfr isn't running and still throws the same error as before, but now I'm certain that the module works as the touchbar is working, but not tiny-dfr.

**Comment by WhatAmISupposedToPutHere** [comment]
Nope, that is a driver issue (kinda). The driver you are using is running the t1 in "windows/boot camp" mode where it manages the tb itself and emulates a keyboard. Tiny-dfr is for running it in "macos" mode, where the os does everything (the only mode available on m1/m2)

**Comment by RealFX-Code** [comment]
Ohhhhh, I'll have to look into that. It works now, and I can finally use escape so I can debug it on the machine itself now and not through SSH. :D

**Comment by WhatAmISupposedToPutHere** [comment]
This is a driver-related bug on t2
