### ISSUE TITLE
The service does not start

### ISSUE THREAD

**Issue by suslik-50** [WhatAmISupposedToPutHere/tiny-dfr#54]
Hi, I have a problem, the service does not start, and when the program starts, the following output is displayed

thread 'main' panicked at src/main.rs:518:43:
called `Result::unwrap()` on an `Err` value: No touchbar device found, attempted: [
    /dev/dri/card1: Permission denied (os error 13),
    /dev/dri/card2: Permission denied (os error 13)
]
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Can you tell me what needs to be done?

**Comment by WhatAmISupposedToPutHere** [comment]
It looks like you are trying to start it as an unprivileged user, it needs to run as root. I recommend figuring out why the service does not start and going from there, running it manually is not recommended.

**Comment by suslik-50** [comment]
Hi, I copied the log , as I understand it, the tiny_dfr_display device is missing, a quick search did not give results, can you tell me what is missing?

 systemd[1]: dev-tiny_dfr_display.device: Job dev-tiny_dfr_display.device/start timed out.
 systemd[1]: Timed out waiting for device dev-tiny_dfr_display.device - /dev/tiny_dfr_display.
 systemd[1]: Dependency failed for tiny-dfr.service - Tiny Apple silicon touch bar daemon.
 systemd[1]: tiny-dfr.service: Job tiny-dfr.service/start failed with result 'dependency'.
 systemd[1]: dev-tiny_dfr_display.device: Job dev-tiny_dfr_display.device/start failed with result 'timeout'.
 systemd[1]: Unnecessary job was removed for dev-tiny_dfr_backlight.device - /dev/tiny_dfr_backlight.

**Comment by WhatAmISupposedToPutHere** [comment]
Is this a T2 or an M1/2 machine?

**Comment by suslik-50** [comment]
This is t2 , macbook pro 16 (2019)

**Comment by WhatAmISupposedToPutHere** [comment]
The touchbar display driver failed to start, and as such, the service does not attempt to start, since from it's pov, the hardware does not exist. I do not maintain the T2 drivers, so you should ask for help on the t2linux discord. https://t2linux.org

**Comment by suslik-50** [comment]
Thanks! I will try to figure it out
