### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by Duarte475** [WhatAmISupposedToPutHere/tiny-dfr#55]
Hi guys,
I have a 13" M1 MacBook Pro (16GB) and the other day after I got a Fedora system update my touchbar stopped working.
I tried to start it manually but it also fails.
I have here a screenshot of the error I'm facing.
![imagem](https://github.com/user-attachments/assets/24ffc645-a66d-4700-8f3d-63f81b3b1001)
I'm a Linux noob so, sorry if I'm the one doing something wrong 😅

**Comment by WhatAmISupposedToPutHere** [comment]
try to start it manually (`sudo tiny-dfr`) and attach the output here.

**Comment by Duarte475** [comment]
I've tried that and it's outputting this
![imagem](https://github.com/user-attachments/assets/9dd0b890-c7e0-4059-88bb-665a15c88c16)
I haven't change any kind of config file

**Comment by WhatAmISupposedToPutHere** [comment]
Do you have displaylink drivers installed? Or any other out of tree kernel modules.

**Comment by Duarte475** [comment]
yes, I have the DisplayLink driver installed and it also stopped working.
I'm starting to feel that I'm the one who borked everything 😅

**Comment by WhatAmISupposedToPutHere** [comment]
https://github.com/WhatAmISupposedToPutHere/tiny-dfr/commit/d5491af2f46dc6b141a1e0107e5f98dd875a6c6a

If you are comfortable compiling it yourself - latest commit should fix it. Alternatively, you can remove the displaylink drivers, or wait for a release that includes the commit above.
