### ISSUE TITLE
Dealing with potential burn-in 

### ISSUE THREAD

**Issue by jonas2515** [WhatAmISupposedToPutHere/tiny-dfr#9]
Since the touch bar is an OLED panel, have there been any thoughts on the potential for burn-in on the panel? Do we know whether macOS does anything special there?

**Comment by WhatAmISupposedToPutHere** [comment]
The burn-in potential is why the idle timeout exists and will not be configurable. I do not do pixel shifting, but iiuc, macos does not either.

**Comment by jonas2515** [comment]
Thing is I'd really like to remove the idle timeout, this is the one thing that'll make the touchbar actually nice :P 

Combined with light sensor reading and very subtle dimming on idle this would make the touch bar so much more usable than on macOS..

One option I'm thinking about would be removing the button outline and then doing pixel shifting, but I get if that's not a direction you'd like to see this project move in.

**Comment by WhatAmISupposedToPutHere** [comment]
Ambient light sensor is not supported on asahi yet, so that needs to be done first. And arguably i overtuned the idle dimming rn, mostly because i was writing the service under artificial light at night, and while the dimmed state is perfectly usable under those lighting conditions, its almost unusable under sunlight.

I am not opposed to pixel shifting in theory, but losing the button outlines sounds like a bad idea, you already do not get tactile feedback on touchbar, unlike on a kb, and being unable to see the hit registration areas would make using it even worse.

**Comment by AdityaGarg8** [comment]
> Thing is I'd really like to remove the idle timeout, this is the one thing that'll make the touchbar actually nice :P
> 
> Combined with light sensor reading and very subtle dimming on idle this would make the touch bar so much more usable than on macOS..
> 
I actually was thinking about making idle timeout configurable in my fork
> One option I'm thinking about would be removing the button outline and then doing pixel shifting, but I get if that's not a direction you'd like to see this project move in.

https://media.discordapp.net/attachments/1107390705430708258/1162113148816465950/3a7d4665-dd09-4ae8-95bd-ce6a73271742.jpg?ex=6543fbb5&is=653186b5&hm=3610e2c680ff44f7ad5fb1e2671b23e8ec6b8828af59aa6093da2a3ed0c237d4&

This mode in my fork is kinda what you want I guess.

**Comment by jonas2515** [comment]
Gave the pixel shifting approach a try now, it works beautifully and is surprisingly not noticeable at all to me: https://github.com/WhatAmISupposedToPutHere/tiny-dfr/pull/12

> losing the button outlines sounds like a bad idea, you already do not get tactile feedback on touchbar, unlike on a kb, and being unable to see the hit registration areas would make using it even worse.

Not sure about that, I see the point about button outlines being useful in normal application UIs, but the touchbar is pretty much physically part of the keyboard from a UX standpoint. Being part of the keyboard makes it fairly natural to expect that something can be clicked IMO, so not sure the button outlines are needed.

I added a commit removing those outlines to the pixel shifting MR now because with the outlines the pixel shifting becomes quite visible...

**Comment by WhatAmISupposedToPutHere** [comment]
We have pixel shifting no, so i guess this is good enough
